apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: opencodequest-templates
  description: A collection of Backstage templates for OpenCodeQuest workshop
spec:
  type: url
  targets:
    - ./fight-ui/template.yaml
    - ./quarkus-postgresql/template.yaml
    - ./quarkus-with-spring-postgresql/template.yaml
    - ./quarkus-ai/template.yaml
